export const GET_RECIPES = 'GET RECIPES'
export const GET_DIETS = 'GET DIETS'
export const CREATE_RECIPE = 'CREATE_RECIPE'
export const SEARCH_RECIPE = 'SEARCH_RECIPE'
export const FILTER_ORIGIN = 'FILTER_ORIGIN'
export const FILTER_DIETS = 'FILTER_DIETS'
export const ORDER = 'ORDER'
export const RESET = 'RESET'
